### 预备
* https://github.com/cdr/code-server/blob/master/Dockerfile
### 

```
FROM codercom/code-server

USER root

RUN apt update && apt upgrade -y && apt install -y openjdk-8-jdk && mkdir /work

WORKDIR /work

VOLUME [ "/work" ]

ENTRYPOINT ["dumb-init", "code-server"]

```
